### ISSUE TITLE
loliserver加载不了Clearentity

### ISSUE THREAD

**Issue by Theagree** [MrLv0816/ClearEntity#1]
![image](https://user-images.githubusercontent.com/84651172/147434641-855acfa0-b4a2-4238-9705-469557a3a023.png)
求作者大大帮忙，用的是LoliServer-1.16.5-a3891ce-server.jar，没有mod插件也只有这个。

**Comment by Theagree** [comment]
[latest.log](https://github.com/MrLv0816/ClearEntity/files/7778321/latest.log)

**Comment by Summer-Tail** [comment]
> ![image](https://user-images.githubusercontent.com/84651172/147434641-855acfa0-b4a2-4238-9705-469557a3a023.png) 求作者大大帮忙，用的是LoliServer-1.16.5-a3891ce-server.jar，没有mod插件也只有这个。

我并没有找到您这个版本,但是我在LoliServer最新构建的版本上测试时没有问题的,您可以把你的这个版本发我一份,或者使用压缩包打开插件编辑 plugin.yml文件中api-version: 1.16 改为 1.13试一下

**Comment by Theagree** [comment]
知道为什么了，用谷歌浏览器在mcbbs下载会导致文件损坏，问题解决了，感恩。
