### ISSUE TITLE
一清理就报错刷屏

### ISSUE THREAD

**Issue by mcmc-erha** [MrLv0816/ClearEntity#11]
![D39JU{7U_WK@{C6`3`Q@DYQ](https://github.com/Summer-Tail/ClearEntity/assets/102884626/541b44ed-0e75-4714-8eed-02fc552b2382)
服务端mohist-1.16.5-151 版本 1.16.5 插件版本2.6.2
[config.txt](https://github.com/Summer-Tail/ClearEntity/files/14150792/config.txt)

**Comment by Summer-Tail** [comment]
不支持 mohist，建议更换 catserver 使用
