### ISSUE TITLE
请求加入新的特性

### ISSUE THREAD

**Issue by DKGhostDark** [MrLv0816/ClearEntity#5]
1.因为有打算将清理交给CMI的计划任务，所以可不可以在config里面提供更改ce clear这个指令需要的60s准备时间的途径
2.关于实体搜索功能，玩rlcraft的时候，尝试寻找书卷之龙的实体名，ce里给出的名字是defiledlands:book_wyrn,而似乎你的另一款插件entitysearch里面提供的实体名称是 book wyrn,最后经过测试，entitysearch插件里面给出的实体名字是正确的，如果使用defiledlands:book_wyrn，插件将不会清理书卷之龙
3.可否加入占位符，用于清除玩家，掉落物以外的所有实体(测试了*这个似乎没有用)

**Comment by Summer-Tail** [comment]
问题1： 60秒倒计时在config是可以更改的 在Message.time节点
问题2：entitysearch和Clearentity所提供的id方式不同 clearentity提供的id是真实的注册id并且清理机制也是围绕这个id来运行的，至于为什么不生效需要详细查看
问题3：可以考虑

**Comment by DKGhostDark** [comment]
不生效估计是设置错误了，后续测试了一下确实后续的清除是根据clearrntity的id进行的，但是至于为什么之前那一次用的是不同的id，估计是bug，插件非常好用，谢谢大佬，然后就是，关于3，之后测试的结果是，也无法通过模组名字+*比如，lycanitesmobs:*来达到清理该模组所有实体的效果。以及就是黑名单和白名单的优先级这个东西能问一下么，比如说，我想清理恐怖怪物里面所有的怪物，但是有那么一两只需要设置白名单不清理，在这种情况下，如果黑名单的优先级更高应该就会清理掉了吧qwq

**Comment by Summer-Tail** [comment]
白名单优先级更高
